# Import

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

# Загрузка данных

In [2]:
sessions_df = pd.read_csv('data/ga_sessions.csv', low_memory=False)
sessions_df.shape

(1860042, 18)

In [3]:
sessions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860042 entries, 0 to 1860041
Data columns (total 18 columns):
 #   Column                    Dtype
---  ------                    -----
 0   session_id                object
 1   client_id                 object
 2   visit_date                object
 3   visit_time                object
 4   visit_number              int64
 5   utm_source                object
 6   utm_medium                object
 7   utm_campaign              object
 8   utm_adcontent             object
 9   utm_keyword               object
 10  device_category           object
 11  device_os                 object
 12  device_brand              object
 13  device_model              object
 14  device_screen_resolution  object
 15  device_browser            object
 16  geo_country               object
 17  geo_city                  object
dtypes: int64(1), object(17)
memory usage: 255.4+ MB

In [3]:
sessions_df.head()

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city
0,9055434745589932991.1637753792.1637753792,2108382700.1637753791,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Zlatoust
1,905544597018549464.1636867290.1636867290,210838531.1636867288,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow
2,9055446045651783499.1640648526.1640648526,2108385331.1640648523,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk
3,9055447046360770272.1622255328.1622255328,2108385564.1622255328,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow

In [4]:
sessions_df.session_id.value_counts()

9055434745589932991.1637753792.1637753792    1
6294640354816492625.1638728787.1638728809    1
6294832296889291185.1623245519.1623245519    1
6294832296889291185.1623161065.1623161065    1
6294832296889291185.1623156608.1623156608    1
                                            ..
3525580570051063315.1625927189.1625927189    1
3525573324456022940.1640876964.1640876964    1
3525573324456022940.1640837067.1640837067    1
3525573324456022940.1640715164.1640715164    1
9055430416266113553.1640968742.1640968742    1
Name: session_id, Length: 1860042, dtype: int64

In [5]:
ga_hits_df = pd.read_csv('data/ga_hits-002.csv', low_memory=False)

In [6]:
ga_hits_df.head()

,session_id,hit_date,hit_time,hit_number,hit_type,hit_referer,hit_page_path,event_category,event_action,event_label,event_value
0,5639623078712724064.1640254056.1640254056,2021-12-23,597864.0,30,event,NaN,sberauto.com/cars?utm_source_initial=google&ut...,quiz,quiz_show,NaN,NaN
1,7750352294969115059.1640271109.1640271109,2021-12-23,597331.0,41,event,NaN,sberauto.com/cars/fiat?city=1&city=18&rental_c...,quiz,quiz_show,NaN,NaN
2,885342191847998240.1640235807.1640235807,2021-12-23,796252.0,49,event,NaN,sberauto.com/cars/all/volkswagen/polo/e994838f...,quiz,quiz_show,NaN,NaN
3,142526202120934167.1640211014.1640211014,2021-12-23,934292.0,46,event,NaN,sberauto.com/cars?utm_source_initial=yandex&ut...,quiz,quiz_show,NaN,NaN
4,3450086108837475701.1640265078.1640265078,2021-12-23,768741.0,79,event,NaN,sberauto.com/cars/all/mercedes-benz/cla-klasse...,quiz,quiz_show,NaN,NaN

# Подготовка датасета ga_hits_df

Оставлю только те признаки, которые нужны для дальнейшей работы

In [7]:
ga_hits_df = ga_hits_df.drop(['hit_type','hit_date', 'hit_time', 'hit_number', 'hit_referer', 'hit_page_path', 'event_category', 'event_label', 'event_value'], axis=1)
ga_hits_df

                                         session_id event_action
0         5639623078712724064.1640254056.1640254056    quiz_show
1         7750352294969115059.1640271109.1640271109    quiz_show
2          885342191847998240.1640235807.1640235807    quiz_show
3          142526202120934167.1640211014.1640211014    quiz_show
4         3450086108837475701.1640265078.1640265078    quiz_show
...                                             ...          ...
15726465  6866159858916559617.1640270865.1640270865    quiz_show
15726466  7310304587364460692.1640261783.1640261783    quiz_show
15726467  8013702685784312179.1640270195.1640270195    quiz_show
15726468  8021505554734405918.1640257821.1640257821    quiz_show
15726469  1569014437485249865.1640269129.1640269129    quiz_show

[15726470 rows x 2 columns]

In [8]:
action_list = ['sub_car_claim_click', 'sub_car_claim_submit_click',
'sub_open_dialog_click', 'sub_custom_question_submit_click',
'sub_call_number_click', 'sub_callback_submit_click', 'sub_submit_success',
'sub_car_request_submit_click']
ga_hits_df['event_action_result'] = ga_hits_df.event_action.apply(lambda x: 1 if x in action_list else 0)

ga_hits_df.event_action_result.value_counts()

0    15621562
1      104908
Name: event_action_result, dtype: int64

In [9]:
ga_hits_df = ga_hits_df.drop('event_action', axis=1)
ga_hits_df.head()

                                  session_id  event_action_result
0  5639623078712724064.1640254056.1640254056                    0
1  7750352294969115059.1640271109.1640271109                    0
2   885342191847998240.1640235807.1640235807                    0
3   142526202120934167.1640211014.1640211014                    0
4  3450086108837475701.1640265078.1640265078                    0

In [10]:
ga_hits_df[ga_hits_df.duplicated()]

                                         session_id  event_action_result
23        3117547552978670057.1640217454.1640217454                    0
32        3282323002617677961.1640266499.1640266499                    0
39         562366956183957396.1640246520.1640246520                    0
42         628849304731384746.1640233987.1640233987                    0
61        2530706414478031710.1640233887.1640233887                    0
...                                             ...                  ...
15726465  6866159858916559617.1640270865.1640270865                    0
15726466  7310304587364460692.1640261783.1640261783                    0
15726467  8013702685784312179.1640270195.1640270195                    0
15726468  8021505554734405918.1640257821.1640257821                    0
15726469  1569014437485249865.1640269129.1640269129                    0

[13941722 rows x 2 columns]

In [11]:
ga_hits_df = ga_hits_df.drop_duplicates()
ga_hits_df.shape

(1784748, 2)

# Объединение двух датасетов

In [12]:
total_df = pd.merge(left=sessions_df, right=ga_hits_df, on='session_id', how='inner')
total_df.head()

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result
0,9055434745589932991.1637753792.1637753792,2108382700.1637753791,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Zlatoust,0
1,905544597018549464.1636867290.1636867290,210838531.1636867288,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow,0
2,9055446045651783499.1640648526.1640648526,2108385331.1640648523,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk,0
3,9055447046360770272.1622255328.1622255328,2108385564.1622255328,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0

In [13]:
total_df[total_df.session_id.duplicated()]

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result
70,9055768928391199041.1623652678.1623652678,2108460508.1623652673,2021-06-14,09:00:00,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,JNHcPlZPxEMWDnRiyoBf,NaN,mobile,NaN,Huawei,NaN,360x780,Chrome,Russia,Moscow,1
75,9055789093275396095.1636395007.1636395007,2108465203.1636395007,2021-11-08,21:10:07,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,JNHcPlZPxEMWDnRiyoBf,puhZPIYqKXeFPaUviSjo,mobile,iOS,Apple,NaN,414x736,Safari,Russia,Samara,1
79,9055794766915104430.1624305327.1624305327,2108466524.1624305326,2021-06-21,22:00:00,1,BHcvLfOaCWvWTykYqHVe,cpc,NaN,NaN,NaN,desktop,NaN,NaN,NaN,834x1112,Safari,Russia,Domodedovo,1
131,9056028189803556573.1630154471.1630154471,2108520872.1630154461,2021-08-28,15:00:00,1,fDLlAcSmythWSCVMvqvL,(none),LTuZkdKfxRGVceoWkVyg,JNHcPlZPxEMWDnRiyoBf,NaN,mobile,NaN,Samsung,NaN,412x915,YaBrowser,Russia,Krasnodar,1
140,9056093322981390023.1628944098.1628944098,2108536037.1628944071,2021-08-14,15:00:00,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,JNHcPlZPxEMWDnRiyoBf,NaN,mobile,NaN,Samsung,NaN,360x740,Chrome,Russia,Moscow,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781856,9054912872702758664.1636781836.1636781836,2108261192.1636781832,2021-11-13,08:37:16,1,kjsLglQLzykiRbcDiGcD,cpc,LwJZxKuWmvOhPsaCeRjG,NaN,HKFjmDlYppkKqsWPogJt,mobile,Android,Xiaomi,NaN,360x800,Chrome,Russia,Moscow,1
1781930,9055248417020050011.1634073188.1634073188,2108339317.1634073179,2021-10-13,00:00:00,1,ZpYIoDJMcFzVoPFsHGJL,banner,SgIUDYUKnyWHVowUOqid,JNHcPlZPxEMWDnRiyoBf,NaN,mobile,NaN,Huawei,NaN,360x780,Chrome,Russia,Nizhny Novgorod,1
1781933,9055248417020050011.1634075541.1634075541,2108339317.1634073179,2021-10-13,00:00:00,3,ZpYIoDJMcFzVoPFsHGJL,banner,SgIUDYUKnyWHVowUOqid,JNHcPlZPxEMWDnRiyoBf,NaN,mobile,NaN,Huawei,NaN,360x780,Chrome,Russia,Nizhny Novgorod,1
1781961,9055376699099939975.1630766214.1630766214,2108369185.1630766215,2021-09-04,17:00:00,1,fDLlAcSmythWSCVMvqvL,(none),LTuZkdKfxRGVceoWkVyg,JNHcPlZPxEMWDnRiyoBf,NaN,desktop,NaN,NaN,NaN,1920x1080,Chrome,Russia,Khimki,1
1781965,9055394269810294140.1629912447.1629912447,2108373276.1629912444,2021-08-25,20:00:00,1,bByPQxmDaMXgpHeypKSM,referral,LTuZkdKfxRGVceoWkVyg,JNHcPlZPxEMWDnRiyoBf,NaN,mobile,NaN,Samsung,NaN,360x800,Android Webview,Russia,Saint Petersburg,1

In [14]:
session_dubl_list = total_df[total_df.session_id.duplicated()].index.tolist()
len(session_dubl_list)

49708

In [15]:
total_df.shape

(1781974, 19)

In [19]:
total_df = total_df[~(total_df.session_id.duplicated())]
total_df.head()

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result
0,9055434745589932991.1637753792.1637753792,2108382700.1637753791,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Zlatoust,0
1,905544597018549464.1636867290.1636867290,210838531.1636867288,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow,0
2,9055446045651783499.1640648526.1640648526,2108385331.1640648523,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk,0
3,9055447046360770272.1622255328.1622255328,2108385564.1622255328,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0

In [20]:
total_df.shape

(1732266, 19)

In [21]:
total_df.device_category.value_counts()

mobile     1368679
desktop     346891
tablet       16696
Name: device_category, dtype: int64

Добавлю в датасет новый признак mobile. Если устройство мобильное, значениями данного признака будет 1, иначе 0.

In [23]:
mobile_list = ['mobile', 'tablet']
total_df['mobile'] = total_df.device_category.apply(lambda x: 1 if x in mobile_list else 0)

total_df.mobile.value_counts()

C:\Users\admin\AppData\Local\Temp\ipykernel_6460\957385368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_df['mobile'] = total_df.device_category.apply(lambda x: 1 if x in mobile_list else 0)

1    1385375
0     346891
Name: mobile, dtype: int64

In [27]:
total_df.dtypes

session_id                  object
client_id                   object
visit_date                  object
visit_time                  object
visit_number                 int64
utm_source                  object
utm_medium                  object
utm_campaign                object
utm_adcontent               object
utm_keyword                 object
device_category             object
device_os                   object
device_brand                object
device_model                object
device_screen_resolution    object
device_browser              object
geo_country                 object
geo_city                    object
event_action_result          int64
mobile                       int64
dtype: object

Добавлю в датасет новый признак, в значениях которого будет информация о днях недели. Если день является выходным днем, в значениях признака будет 1, иначе 0.

In [28]:
total_df['week_day'] = pd.to_datetime(total_df['visit_date'])
total_df.dtypes

C:\Users\admin\AppData\Local\Temp\ipykernel_6460\3107272009.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_df['week_day'] = pd.to_datetime(total_df['visit_date'])

session_id                          object
client_id                           object
visit_date                          object
visit_time                          object
visit_number                         int64
utm_source                          object
utm_medium                          object
utm_campaign                        object
utm_adcontent                       object
utm_keyword                         object
device_category                     object
device_os                           object
device_brand                        object
device_model                        object
device_screen_resolution            object
device_browser                      object
geo_country                         object
geo_city                            object
event_action_result                  int64
mobile                               int64
week_day                    datetime64[ns]
dtype: object

In [30]:
total_df['week_day'] = total_df['week_day'].dt.weekday

In [31]:
total_df.head()

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,...,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result,mobile,week_day
0,9055434745589932991.1637753792.1637753792,2108382700.1637753791,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,...,Android,Huawei,NaN,360x720,Chrome,Russia,Zlatoust,0,1,2
1,905544597018549464.1636867290.1636867290,210838531.1636867288,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,...,Android,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow,0,1,6
2,9055446045651783499.1640648526.1640648526,2108385331.1640648523,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,...,Android,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk,0,1,1
3,9055447046360770272.1622255328.1622255328,2108385564.1622255328,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,...,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0,1,5
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,...,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0,1,5

In [34]:
weekend_list = [5, 6]
total_df['weekend'] = total_df.week_day.apply(lambda x: 1 if x in weekend_list else 0)
total_df.head()

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,...,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result,mobile,week_day,weekend
0,9055434745589932991.1637753792.1637753792,2108382700.1637753791,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,...,Huawei,NaN,360x720,Chrome,Russia,Zlatoust,0,1,2,0
1,905544597018549464.1636867290.1636867290,210838531.1636867288,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,...,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow,0,1,6,1
2,9055446045651783499.1640648526.1640648526,2108385331.1640648523,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,...,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk,0,1,1,0
3,9055447046360770272.1622255328.1622255328,2108385564.1622255328,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,...,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0,1,5,1
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,...,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0,1,5,1

Добавлю в датасет еще признак, в котором будет информация об активности по посещаемости. Если посещаемость больше 4500, значениями признака будут 1, иначе 0.

In [78]:
# city_list = total_df.geo_city.unique().tolist()

# new_city_list = [item for item in city_list if (len(total_df[total_df['geo_city'] == item]) > 4500)]
# new_city_list

In [79]:
city_count_df = total_df.geo_city.value_counts().to_frame()
city_count_df.head()

                  geo_city
Moscow              750928
Saint Petersburg    278402
(not set)            73297
Yekaterinburg        33555
Krasnodar            30260

In [80]:
city_count_list = city_count_df[city_count_df['geo_city'] > 4500].index.tolist()
city_count_list

['Moscow',
 'Saint Petersburg',
 '(not set)',
 'Yekaterinburg',
 'Krasnodar',
 'Kazan',
 'Samara',
 'Nizhny Novgorod',
 'Ufa',
 'Novosibirsk',
 'Krasnoyarsk',
 'Chelyabinsk',
 'Tula',
 'Rostov-on-Don',
 'Voronezh',
 'Irkutsk',
 'Grozny',
 'Balashikha',
 'Vladivostok',
 'Yaroslavl',
 'Sochi',
 'Tyumen',
 'Khimki',
 'Saratov',
 'Perm',
 'Vidnoye',
 'Odintsovo',
 'Mytishchi',
 'Izhevsk',
 'Zheleznodorozhny']

In [81]:
total_df['most_visited_city'] = total_df.geo_city.apply(lambda x: 1 if x in city_count_list else 0)
total_df.head()

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,...,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result,mobile,week_day,weekend,most_visited_city
0,9055434745589932991.1637753792.1637753792,2108382700.1637753791,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,...,NaN,360x720,Chrome,Russia,Zlatoust,0,1,2,0,0
1,905544597018549464.1636867290.1636867290,210838531.1636867288,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,...,NaN,385x854,Samsung Internet,Russia,Moscow,0,1,6,1,1
2,9055446045651783499.1640648526.1640648526,2108385331.1640648523,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,...,NaN,360x720,Chrome,Russia,Krasnoyarsk,0,1,1,0,1
3,9055447046360770272.1622255328.1622255328,2108385564.1622255328,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,...,NaN,393x786,Chrome,Russia,Moscow,0,1,5,1,1
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,...,NaN,393x786,Chrome,Russia,Moscow,0,1,5,1,1

Еще из датасета удалю строки, в которых дублируются client_id и visit_time. В основном строки полностью дублируются

In [86]:
total_df[total_df[['client_id', 'visit_time']].duplicated()]

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,...,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result,mobile,week_day,weekend,most_visited_city
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,...,NaN,393x786,Chrome,Russia,Moscow,0,1,5,1,1
22,9055497958914887309.1634046980.1634046980,2108397418.1634045581,2021-10-12,16:00:00,2,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,NaN,...,NaN,393x851,Chrome,Russia,Moscow,0,1,1,0,1
25,9055497958914887309.1634224644.1634224644,2108397418.1634045581,2021-10-14,18:00:00,5,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,NaN,...,NaN,393x851,Chrome,Russia,Moscow,0,1,3,0,1
30,9055507072827135870.1625694582.1625694582,2108399540.1625692030,2021-07-08,00:00:00,2,fDLlAcSmythWSCVMvqvL,(none),LTuZkdKfxRGVceoWkVyg,JNHcPlZPxEMWDnRiyoBf,NaN,...,NaN,393x699,Chrome,Russia,Pushkino,0,1,3,0,0
33,9055511191703531814.1628451239.1628451239,2108400499.1628451110,2021-08-08,22:00:00,2,klTrhUaShgnjIbaPmqjc,referral,LTuZkdKfxRGVceoWkVyg,JNHcPlZPxEMWDnRiyoBf,NaN,...,NaN,375x667,Safari (in-app),Russia,Moscow,0,1,6,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781910,9055186307496642446.1632733094.1632733094,2108324856.1632733070,2021-09-27,11:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,...,NaN,390x844,Safari,Russia,Krasnogorsk,0,1,0,0,0
1781918,9055216346490282940.1625105400.1625105400,2108331850.1625105340,2021-07-01,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,...,NaN,1920x1080,Chrome,Russia,Moscow,0,0,3,0,1
1781931,9055248417020050011.1634075504.1634075504,2108339317.1634073179,2021-10-13,00:00:00,2,ZpYIoDJMcFzVoPFsHGJL,banner,gecBYcKZCPMcVYdSSzKP,JNHcPlZPxEMWDnRiyoBf,NaN,...,NaN,360x780,Chrome,Russia,Nizhny Novgorod,0,1,2,0,1
1781932,9055248417020050011.1634075541.1634075541,2108339317.1634073179,2021-10-13,00:00:00,3,ZpYIoDJMcFzVoPFsHGJL,banner,SgIUDYUKnyWHVowUOqid,JNHcPlZPxEMWDnRiyoBf,NaN,...,NaN,360x780,Chrome,Russia,Nizhny Novgorod,0,1,2,0,1
1781935,9055248417020050011.1634078414.1634078414,2108339317.1634073179,2021-10-13,01:00:00,5,ZpYIoDJMcFzVoPFsHGJL,banner,gecBYcKZCPMcVYdSSzKP,JNHcPlZPxEMWDnRiyoBf,NaN,...,NaN,360x780,Chrome,Russia,Nizhny Novgorod,0,1,2,0,1

In [87]:
total_df = total_df[~(total_df[['client_id', 'visit_time']].duplicated())]
total_df.shape

(1635428, 23)

Оставлю в датасете только необходимые признаки, исходные датасеты удалю

In [89]:
drop_list = ['session_id', 'client_id', 'visit_date', 'visit_time', 'visit_number', 'week_day']
total_df = total_df.drop(drop_list, axis=1)
sessions_df = pd.DataFrame()
ga_hits_df = pd.DataFrame()

In [90]:
total_df.head()

,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city,event_action_result,mobile,weekend,most_visited_city
0,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Zlatoust,0,1,0,0
1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow,0,1,1,1
2,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk,0,1,0,1
3,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow,0,1,1,1
5,kjsLglQLzykiRbcDiGcD,organic,LTuZkdKfxRGVceoWkVyg,JNHcPlZPxEMWDnRiyoBf,NaN,mobile,NaN,Apple,NaN,375x812,Safari,Russia,Saint Petersburg,0,1,0,1

# Замена пропусков

## Подсчет пропусков

In [91]:
total_df.isna().sum()

utm_source                       76
utm_medium                        0
utm_campaign                 155497
utm_adcontent                254919
utm_keyword                  923939
device_category                   0
device_os                    917151
device_brand                 315108
device_model                1620367
device_screen_resolution          0
device_browser                    0
geo_country                       0
geo_city                          0
event_action_result               0
mobile                            0
weekend                           0
most_visited_city                 0
dtype: int64

In [92]:
(total_df.isna().sum() / len(total_df) * 100).sort_values()

most_visited_city            0.000000
utm_medium                   0.000000
mobile                       0.000000
event_action_result          0.000000
geo_city                     0.000000
device_category              0.000000
geo_country                  0.000000
device_browser               0.000000
weekend                      0.000000
device_screen_resolution     0.000000
utm_source                   0.004647
utm_campaign                 9.508031
utm_adcontent               15.587296
device_brand                19.267617
device_os                   56.080182
utm_keyword                 56.495242
device_model                99.079079
dtype: float64

## Замена пропусков для признаков utm_*

In [93]:
columns_for_preparing = [
    'utm_source',
    'utm_campaign',
    'utm_adcontent',
    'utm_keyword'
    ]

for item in columns_for_preparing:
    nan_df = pd.DataFrame()
    nan_list = []
    nan_dict = {}

    nan_df[['utm_medium', item]] = total_df[total_df[item].isna()][['utm_medium', item]]
    nan_list = nan_df['utm_medium'].unique().tolist()

    max_utm_index_value = total_df[item].mode().tolist()[0]
    for nan_list_index in nan_list:
        max_value = total_df[total_df['utm_medium'] == nan_list_index][item].mode().tolist()
        if max_value == []:
            nan_dict[nan_list_index] = max_utm_index_value
        else:
            nan_dict[nan_list_index] = max_value[0]

    for j_key, j_value in nan_dict.items():
        nan_index_list = []
        nan_index_list = nan_df[nan_df['utm_medium'] == j_key].index.tolist()
        total_df.loc[nan_index_list, item] = j_value

In [94]:
(total_df.isna().sum() / len(total_df) * 100).sort_values()

utm_source                   0.000000
mobile                       0.000000
event_action_result          0.000000
geo_city                     0.000000
geo_country                  0.000000
device_browser               0.000000
device_screen_resolution     0.000000
weekend                      0.000000
most_visited_city            0.000000
device_category              0.000000
utm_keyword                  0.000000
utm_adcontent                0.000000
utm_campaign                 0.000000
utm_medium                   0.000000
device_brand                19.267617
device_os                   56.080182
device_model                99.079079
dtype: float64

## Замена пропусков для признака device_brand

In [95]:
nan_df = pd.DataFrame()
nan_df[['device_category', 'device_os', 'device_brand', 'device_model', 'device_screen_resolution', 'device_browser']] = total_df[total_df.device_brand.isna()][['device_category', 'device_os', 'device_brand', 'device_model', 'device_screen_resolution', 'device_browser']]
nan_df

,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser
28,desktop,Windows,NaN,NaN,1536x864,Chrome
61,desktop,NaN,NaN,NaN,1920x1080,YaBrowser
62,desktop,NaN,NaN,NaN,1920x1080,Chrome
65,desktop,Windows,NaN,NaN,1920x1080,Chrome
72,desktop,NaN,NaN,NaN,1280x720,Chrome
...,...,...,...,...,...,...
1781956,desktop,Windows,NaN,NaN,1366x768,Firefox
1781958,desktop,NaN,NaN,NaN,1920x1080,Chrome
1781960,desktop,NaN,NaN,NaN,1920x1080,Chrome
1781969,desktop,Windows,NaN,NaN,1920x1080,Chrome
1781973,desktop,Linux,NaN,NaN,1366x768,Chrome

In [96]:
device_category_list = []
device_category_list = nan_df['device_category'].unique().tolist()
device_category_list

['desktop', 'mobile', 'tablet']

In [97]:
brand_dict_browser = {}
for index in device_category_list:
    brand_dict_browser[index] = nan_df[nan_df['device_category'] == index].device_browser.unique().tolist()
brand_dict_browser

{'desktop': ['Chrome',
  'YaBrowser',
  'Safari',
  'Firefox',
  'Opera',
  'Edge',
  'helloworld',
  'Samsung Internet',
  'Instagram 208.0.0.32.135 Android',
  'Mozilla Compatible Agent',
  '(not set)',
  'Coc Coc',
  'Android',
  'Instagram 216.1.0.21.137 Android',
  '[FBAN',
  'Internet Explorer',
  'MRCHROME',
  'Instagram 209.0.0.21.119 Android',
  'Instagram 213.0.0.29.120 Android',
  'Puffin',
  'Instagram 199.1.0.34.119 Android',
  'Maxthon',
  'SeaMonkey',
  'Instagram 194.0.0.36.172 Android',
  'Instagram 202.0.0.37.123 Android',
  'Mozilla',
  'Instagram 192.0.0.35.123 Android',
  'Instagram 212.0.0.38.119 Android',
  'Instagram 158.0.0.30.123 Android',
  'Konqueror',
  'UC Browser'],
 'mobile': ['Chrome',
  'Safari',
  'Samsung Internet',
  'Edge',
  'Firefox',
  'YaBrowser',
  'Opera',
  'UC Browser'],
 'tablet': ['Safari', 'Chrome', 'Samsung Internet', 'Opera']}

In [98]:
brand_dict = {}
for j_key_1, j_value_1 in brand_dict_browser.items():
    brand_dict_1 = {}
    df_category = pd.DataFrame()
    df_category = total_df[total_df['device_category'] == j_key_1]
    category_os_list = df_category.device_os.mode().tolist()
    for index in j_value_1:
        df_browser = pd.DataFrame()
        df_browser = df_category[df_category['device_browser'] == index]
        browser_os_list = df_browser.device_os.mode().tolist()
        max_value = df_browser.device_brand.mode().tolist()
        if max_value == []:
            brand_dict_1[index] = category_os_list[0] + '_based'
        elif browser_os_list[0] == 'iOS' or browser_os_list[0] == 'Macintosh':    
            brand_dict_1[index] = 'Apple'
        elif browser_os_list[0] == 'Android':
            brand_dict_1[index] = 'Samsung'
        else:
            brand_dict_1[index] = max_value[0]
    brand_dict[j_key_1] = brand_dict_1    

brand_dict

{'desktop': {'Chrome': 'Huawei',
  'YaBrowser': 'Xiaomi',
  'Safari': 'Apple',
  'Firefox': 'Windows_based',
  'Opera': 'Philips',
  'Edge': 'Windows_based',
  'helloworld': 'Windows_based',
  'Samsung Internet': '(not set)',
  'Instagram 208.0.0.32.135 Android': 'Windows_based',
  'Mozilla Compatible Agent': 'Windows_based',
  '(not set)': 'Windows_based',
  'Coc Coc': 'Windows_based',
  'Android': 'Windows_based',
  'Instagram 216.1.0.21.137 Android': 'Windows_based',
  '[FBAN': 'Windows_based',
  'Internet Explorer': 'Windows_based',
  'MRCHROME': 'Windows_based',
  'Instagram 209.0.0.21.119 Android': 'Windows_based',
  'Instagram 213.0.0.29.120 Android': 'Windows_based',
  'Puffin': 'Windows_based',
  'Instagram 199.1.0.34.119 Android': 'Windows_based',
  'Maxthon': 'Windows_based',
  'SeaMonkey': 'Windows_based',
  'Instagram 194.0.0.36.172 Android': 'Windows_based',
  'Instagram 202.0.0.37.123 Android': 'Windows_based',
  'Mozilla': 'Windows_based',
  'Instagram 192.0.0.35.123 Android': 'Windows_based',
  'Instagram 212.0.0.38.119 Android': 'Windows_based',
  'Instagram 158.0.0.30.123 Android': 'Windows_based',
  'Konqueror': 'Windows_based',
  'UC Browser': 'Windows_based'},
 'mobile': {'Chrome': 'Samsung',
  'Safari': 'Apple',
  'Samsung Internet': 'Samsung',
  'Edge': 'Apple',
  'Firefox': 'Samsung',
  'YaBrowser': 'Samsung',
  'Opera': 'Samsung',
  'UC Browser': 'Samsung'},
 'tablet': {'Safari': 'Apple',
  'Chrome': 'Samsung',
  'Samsung Internet': 'Samsung',
  'Opera': 'Samsung'}}

In [99]:
for j_key_1, j_value_1 in brand_dict.items():
    df_category = pd.DataFrame()
    df_category = nan_df[nan_df['device_category'] == j_key_1]
    for j_key_2, j_value_2 in j_value_1.items():
        nan_index_list = []
        nan_index_list = df_category[df_category['device_browser'] == j_key_2].index.tolist()
        total_df.loc[nan_index_list, 'device_brand'] = j_value_2
        
total_df.device_brand.value_counts(dropna=False)

Apple            504607
Huawei           353220
Xiaomi           311951
Samsung          299921
Windows_based     27786
                  ...
Tesla                 1
Vodafone              1
Wexler                1
Smarteo               1
Maxvi                 1
Name: device_brand, Length: 201, dtype: int64

## Замена пропусков для признака device_os

In [100]:
nan_df = pd.DataFrame()
nan_df[['device_category', 'device_os', 'device_brand', 'device_model', 'device_screen_resolution', 'device_browser']] = total_df[total_df.device_os.isna()][['device_category', 'device_os', 'device_brand', 'device_model', 'device_screen_resolution', 'device_browser']]
nan_df

,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser
3,mobile,NaN,Xiaomi,NaN,393x786,Chrome
5,mobile,NaN,Apple,NaN,375x812,Safari
7,mobile,NaN,Samsung,NaN,360x640,Chrome
9,mobile,NaN,Samsung,NaN,412x915,Chrome
10,mobile,NaN,Samsung,NaN,412x915,Chrome
...,...,...,...,...,...,...
1781962,mobile,NaN,Xiaomi,NaN,393x851,Chrome
1781964,mobile,NaN,Samsung,NaN,360x800,Android Webview
1781967,mobile,NaN,Apple,NaN,414x896,Safari
1781968,mobile,NaN,Samsung,NaN,320x676,Chrome
1781970,mobile,NaN,Apple,NaN,390x844,Safari

In [101]:
device_category_list = []
device_category_list = nan_df['device_category'].unique().tolist()
device_category_list

['mobile', 'tablet', 'desktop']

In [102]:
category_brand_dict = {}
for index in device_category_list:
    category_brand_dict[index] = nan_df[nan_df['device_category'] == index].device_brand.unique().tolist()
category_brand_dict

{'mobile': ['Xiaomi',
  'Apple',
  'Samsung',
  'Huawei',
  'Vivo',
  '(not set)',
  'BQ',
  'OnePlus',
  'itel',
  'Asus',
  'Sony',
  'LG',
  'OPPO',
  'Nokia',
  'Alcatel',
  'Infinix',
  'Micromax',
  'Realme',
  'Blackview',
  'Oukitel',
  'ZTE',
  'Motorola',
  'HOMTOM',
  'Google',
  'China Phone',
  'Neffos',
  'Tecno',
  'DOOGEE',
  'Vsmart',
  'Meizu',
  'BlackBerry',
  'Umidigi',
  'Leagoo',
  'Highscreen',
  'Ulefone',
  'Cubot',
  'Symphony',
  'Lenovo',
  'Vestel',
  'Guophone',
  'Wileyfox',
  'Vertex',
  'POCO',
  'TCL',
  'HTC',
  'SonyEricsson',
  'TP-Link',
  'Nomu',
  'Prestigio',
  'Philips',
  'LeEco',
  'DEXP',
  'Hisense',
  'Tele2',
  'CAT',
  'Kyocera',
  'Inoi',
  'Mozilla',
  'Sharp',
  'MTC',
  'iNew',
  'Vernee',
  'Karbonn',
  'Gionee',
  'Digma',
  'Yota Devices',
  'Kata',
  'Poptel',
  'AGM',
  'Fly',
  'MLS',
  'LeTV',
  'Nuu',
  'Celkon',
  'Walton',
  'Haier',
  'Xiaolajiao',
  'Lava',
  'General Mobile',
  'Black Fox',
  'Condor',
  'Razer',
  'Fujitsu',
  'Coolpad',
  'ZOJI',
  'PPTV',
  'Jiake',
  'Mito',
  'Pantech',
  'NOA',
  'Caterpillar',
  'SenseIT',
  'Wiko',
  'Oysters',
  'Komu',
  'BLU',
  'AT&T',
  'Tonbux',
  'Dark',
  'Elephone',
  'T-Mobile',
  'Smartfren',
  'Billion',
  'Gome',
  'A1',
  'MTS',
  'Geotel',
  'BLUBOO',
  'Acer',
  'Ananda',
  'Ark',
  'Essential',
  'E&L',
  'Fero',
  'Wigor',
  'Mlais',
  'Smartisan',
  'Unihertz',
  'Orbic',
  'MediaTek',
  'Honeywell',
  'RED',
  'Sonim',
  'Jiayu',
  'Kingplay',
  'QMobile',
  'INUI',
  'Artel',
  'China Mobile',
  'Olla',
  'Star',
  'Iris',
  'Microsoft',
  'LTC',
  'Motive',
  'Advan',
  'UMI',
  'M-HORSE',
  'Irbis',
  'ThL',
  'Nomi',
  'Wings Mobile',
  'Centric',
  'Maze',
  'Corn',
  'Gretel',
  'Vertu',
  'Qbex',
  'Panasonic',
  'Maxvi',
  'MXQ'],
 'tablet': ['Apple',
  'Samsung',
  'Lenovo',
  'Google',
  'Huawei',
  'Tecno',
  'Sony',
  '(not set)',
  'Asus',
  'Xiaomi',
  'H96',
  'Kingplay',
  'Flylion',
  'Teclast',
  'Itoos',
  'LG',
  'Chuwi',
  'Acer',
  'Alldocube',
  'Amazon',
  'BQ',
  'DOOGEE',
  'Cube',
  'Leagoo',
  'itel',
  'Alcatel',
  'Cubot',
  'MediaTek',
  'ZTE',
  'Dragon Touch',
  'Land Rover',
  'Tanix',
  'Nomu',
  'InFocus',
  'Prestigio',
  'Archos',
  'Symphony',
  'OnePlus',
  'Evertek',
  'DEXP',
  'Oysters',
  'Irbis',
  'Flexymove',
  'Philips',
  'OPPO',
  'Realme',
  'Winnovo',
  'MXQ',
  'How',
  'Meizu',
  'China TVBox',
  'ThL',
  'Evercoss',
  'Tagital'],
 'desktop': ['Xiaomi',
  'Huawei',
  'Apple',
  'Windows_based',
  'Philips',
  '(not set)',
  'Samsung',
  'Nokia',
  'Asus',
  'Beelink',
  'OPPO',
  'OnePlus',
  'Realme']}

In [103]:
brand_os_dict = {}
for j_key, j_value in category_brand_dict.items():
    brand_os_dict_1 = {}
    category_df = pd.DataFrame()
    category_df = total_df[total_df['device_category'] == j_key]
    max_device_os_value = category_df.device_os.mode().tolist()[0]
    for index in j_value:
        
        max_value = category_df[category_df['device_brand'] == index].device_os.mode().tolist()
        if max_value == []:
            brand_os_dict_1[index] = max_device_os_value
        else:
            brand_os_dict_1[index] = max_value[0]
    brand_os_dict[j_key] = brand_os_dict_1
brand_os_dict

{'mobile': {'Xiaomi': 'Android',
  'Apple': 'iOS',
  'Samsung': 'Android',
  'Huawei': 'Android',
  'Vivo': 'Android',
  '(not set)': 'Android',
  'BQ': 'Android',
  'OnePlus': 'Android',
  'itel': 'Android',
  'Asus': 'Android',
  'Sony': 'Android',
  'LG': 'Android',
  'OPPO': 'Android',
  'Nokia': 'Android',
  'Alcatel': 'Android',
  'Infinix': 'Android',
  'Micromax': 'Android',
  'Realme': 'Android',
  'Blackview': 'Android',
  'Oukitel': 'Android',
  'ZTE': 'Android',
  'Motorola': 'Android',
  'HOMTOM': 'Android',
  'Google': 'Android',
  'China Phone': 'Android',
  'Neffos': 'Android',
  'Tecno': 'Android',
  'DOOGEE': 'Android',
  'Vsmart': 'Android',
  'Meizu': 'Android',
  'BlackBerry': 'Android',
  'Umidigi': 'Android',
  'Leagoo': 'Android',
  'Highscreen': 'Android',
  'Ulefone': 'Android',
  'Cubot': 'Android',
  'Symphony': 'Android',
  'Lenovo': 'Android',
  'Vestel': 'Android',
  'Guophone': 'Android',
  'Wileyfox': 'Android',
  'Vertex': 'Android',
  'POCO': 'Android',
  'TCL': 'Android',
  'HTC': 'Android',
  'SonyEricsson': 'Android',
  'TP-Link': 'Android',
  'Nomu': 'Android',
  'Prestigio': 'Android',
  'Philips': 'Android',
  'LeEco': 'Android',
  'DEXP': 'Android',
  'Hisense': 'Android',
  'Tele2': 'Android',
  'CAT': 'Android',
  'Kyocera': 'Android',
  'Inoi': 'Android',
  'Mozilla': 'Android',
  'Sharp': 'Android',
  'MTC': 'Android',
  'iNew': 'Android',
  'Vernee': 'Android',
  'Karbonn': 'Android',
  'Gionee': 'Android',
  'Digma': 'Android',
  'Yota Devices': 'Android',
  'Kata': 'Android',
  'Poptel': 'Android',
  'AGM': 'Android',
  'Fly': 'Android',
  'MLS': 'Android',
  'LeTV': 'Android',
  'Nuu': 'Android',
  'Celkon': 'Android',
  'Walton': 'Android',
  'Haier': 'Android',
  'Xiaolajiao': 'Android',
  'Lava': 'Android',
  'General Mobile': 'Android',
  'Black Fox': 'Android',
  'Condor': 'Android',
  'Razer': 'Android',
  'Fujitsu': 'Android',
  'Coolpad': 'Android',
  'ZOJI': 'Android',
  'PPTV': 'Android',
  'Jiake': 'Android',
  'Mito': 'Android',
  'Pantech': 'Android',
  'NOA': 'Android',
  'Caterpillar': 'Android',
  'SenseIT': 'Android',
  'Wiko': 'Android',
  'Oysters': 'Android',
  'Komu': 'Android',
  'BLU': 'Android',
  'AT&T': 'Android',
  'Tonbux': 'Android',
  'Dark': 'Android',
  'Elephone': 'Android',
  'T-Mobile': 'Android',
  'Smartfren': 'Android',
  'Billion': 'Android',
  'Gome': 'Android',
  'A1': 'Android',
  'MTS': 'Android',
  'Geotel': 'Android',
  'BLUBOO': 'Android',
  'Acer': 'Android',
  'Ananda': 'Android',
  'Ark': 'Android',
  'Essential': 'Android',
  'E&L': 'Android',
  'Fero': 'Android',
  'Wigor': 'Android',
  'Mlais': 'Android',
  'Smartisan': 'Android',
  'Unihertz': 'Android',
  'Orbic': 'Android',
  'MediaTek': 'Android',
  'Honeywell': 'Android',
  'RED': 'Android',
  'Sonim': 'Android',
  'Jiayu': 'Android',
  'Kingplay': 'Android',
  'QMobile': 'Android',
  'INUI': 'Android',
  'Artel': 'Android',
  'China Mobile': 'Android',
  'Olla': 'Android',
  'Star': 'Android',
  'Iris': 'Android',
  'Microsoft': 'Android',
  'LTC': 'Android',
  'Motive': 'Android',
  'Advan': 'Android',
  'UMI': 'Android',
  'M-HORSE': 'Android',
  'Irbis': 'Android',
  'ThL': 'Android',
  'Nomi': 'Android',
  'Wings Mobile': 'Android',
  'Centric': 'Android',
  'Maze': 'Android',
  'Corn': 'Android',
  'Gretel': 'Android',
  'Vertu': 'Android',
  'Qbex': 'Android',
  'Panasonic': 'Android',
  'Maxvi': 'Android',
  'MXQ': 'Android'},
 'tablet': {'Apple': 'iOS',
  'Samsung': 'Android',
  'Lenovo': 'Android',
  'Google': 'Android',
  'Huawei': 'Android',
  'Tecno': 'Android',
  'Sony': 'Android',
  '(not set)': 'Android',
  'Asus': 'Android',
  'Xiaomi': 'Android',
  'H96': 'Android',
  'Kingplay': 'Android',
  'Flylion': 'Android',
  'Teclast': 'Android',
  'Itoos': 'Android',
  'LG': 'Android',
  'Chuwi': 'Android',
  'Acer': 'Android',
  'Alldocube': 'Android',
  'Amazon': 'Android',
  'BQ': 'Android',
  'DOOGEE': 'Android',
  'Cube': 'Android',
  'Leagoo': 'Android',
  'itel': 'Android',
  'Alcatel': 'Android',
  'Cubot': 'Android',
  'MediaTek': 'Android',
  'ZTE': 'Android',
  'Dragon Touch': 'Android',
  'Land Rover': 'Android',
  'Tanix': 'Android',
  'Nomu': 'Android',
  'InFocus': 'Android',
  'Prestigio': 'Android',
  'Archos': 'Android',
  'Symphony': 'Android',
  'OnePlus': 'Android',
  'Evertek': 'Android',
  'DEXP': 'Android',
  'Oysters': 'Android',
  'Irbis': 'Android',
  'Flexymove': 'Android',
  'Philips': 'Android',
  'OPPO': 'Android',
  'Realme': 'Android',
  'Winnovo': 'Android',
  'MXQ': 'Android',
  'How': 'Android',
  'Meizu': 'Android',
  'China TVBox': 'Android',
  'ThL': 'Android',
  'Evercoss': 'Android',
  'Tagital': 'Android'},
 'desktop': {'Xiaomi': 'Windows',
  'Huawei': 'Windows',
  'Apple': 'Macintosh',
  'Windows_based': 'Windows',
  'Philips': 'Windows',
  '(not set)': 'Linux',
  'Samsung': 'Android',
  'Nokia': 'Windows',
  'Asus': 'Windows',
  'Beelink': 'Windows',
  'OPPO': 'Windows',
  'OnePlus': 'Windows',
  'Realme': 'Android'}}

In [104]:
for j_key_1, j_value_1 in brand_os_dict.items():
    df_category = pd.DataFrame()
    df_category = nan_df[nan_df['device_category'] == j_key_1]
    for j_key_2, j_value_2 in j_value_1.items():
        nan_index_list = []
        nan_index_list = df_category[df_category['device_brand'] == j_key_2].index.tolist()
        total_df.loc[nan_index_list, 'device_os'] = j_value_2
total_df.device_os.value_counts(dropna=False)

Android          850411
iOS              470118
Windows          264455
Macintosh         45246
Linux              4784
(not set)           309
Chrome OS            65
BlackBerry           24
Tizen                 7
Firefox OS            3
Nokia                 2
Samsung               2
Windows Phone         2
Name: device_os, dtype: int64

## Признак device_model

Данный признак удалю, т.к. пропуски для данного признака составляют больше 50%

In [105]:
total_df = total_df.drop('device_model', axis=1)

In [106]:
(total_df.isna().sum() / len(total_df) * 100).sort_values()

utm_source                  0.0
utm_medium                  0.0
utm_campaign                0.0
utm_adcontent               0.0
utm_keyword                 0.0
device_category             0.0
device_os                   0.0
device_brand                0.0
device_screen_resolution    0.0
device_browser              0.0
geo_country                 0.0
geo_city                    0.0
event_action_result         0.0
mobile                      0.0
weekend                     0.0
most_visited_city           0.0
dtype: float64

Переименую названия столбцов

In [107]:
total_df = total_df.rename(columns={'utm_source': 'source', 'utm_medium': 'medium', 'utm_campaign': 'campaign', 
                                    'utm_adcontent': 'adcontent', 'utm_keyword': 'keyword', 'device_category': 'category',
                                   'device_brand': 'brand', 'device_os': 'os', 'device_screen_resolution': 'dsr', 
                                   'device_browser': 'browser', 'geo_country': 'country', 'geo_city': 'city', 
                                    'event_action_result': 'target'})

total_df.head()

,source,medium,campaign,adcontent,keyword,category,os,brand,dsr,browser,country,city,target,mobile,weekend,most_visited_city
0,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,360x720,Chrome,Russia,Zlatoust,0,1,0,0
1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,385x854,Samsung Internet,Russia,Moscow,0,1,1,1
2,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,360x720,Chrome,Russia,Krasnoyarsk,0,1,0,1
3,kjsLglQLzykiRbcDiGcD,cpc,XHNUiSKKGTEpSAlaVMFQ,NOBKLgtuvqYWkXQHeYWM,puhZPIYqKXeFPaUviSjo,mobile,Android,Xiaomi,393x786,Chrome,Russia,Moscow,0,1,1,1
5,kjsLglQLzykiRbcDiGcD,organic,LTuZkdKfxRGVceoWkVyg,JNHcPlZPxEMWDnRiyoBf,aXQzDWsJuGXeBXexNHjc,mobile,iOS,Apple,375x812,Safari,Russia,Saint Petersburg,0,1,0,1

In [108]:
total_df.to_csv('data/total_df.csv', index=False)

# Уменьшение количества уникальных значений признаков

В каждом признаке датафрейма есть уникальные категориальные значения, которые встречаются довольно таки редко, если сравнивать с размером всего признака. Каждое категориальное уникальное значение требует дополнительный столбец при подготовке датафрейма к моделированию, что приводит к сильному увеличению размера датафрейма. В данном случае заменю уникальные значения, которые втречаютсся реже 1000 раз в признаке самым популярным значением в признаке.

In [109]:
device_df = pd.DataFrame()

col_list = ["source", "medium", "campaign", "adcontent", "keyword"]
#                 "os", "brand", "dsr", "browser", "country", "city"]

device_df[col_list] = total_df[col_list]
for item in col_list:
    item_df = pd.DataFrame()
    item_list = []

    item_df['name'] = device_df.groupby(by=[item], as_index=False)[item].max()
    item_df['count'] = device_df.groupby(by=[item], as_index=False)[item].count()
    item_list = item_df[item_df['count'] < 1000].name.tolist()
    most_popular_item = device_df[item].mode().tolist()[0]

    for index_1 in item_list:
        item_index_list = []
        item_index_list = device_df[device_df[item] == index_1].index.tolist()
        device_df.loc[item_index_list, item] = most_popular_item

    total_df[item] = device_df[item].apply(lambda x: x)
    print(item)

source
medium
campaign
adcontent
keyword

In [110]:
total_df.campaign.value_counts(dropna=False)

LTuZkdKfxRGVceoWkVyg    440150
LEoPHuyFvzoNfnzGgfcd    319776
FTjNLDyTrXaWYgZymFkV    233103
XHNUiSKKGTEpSAlaVMFQ    171381
gecBYcKZCPMcVYdSSzKP    131809
                         ...
WJUKqfeOrjXIOHjgcgdR      1123
UKNBOHebRIIsQRsjNKay      1119
EvhrtRzIJnQYHziPiLzV      1047
XwZreaZvgptCcKQsSTmK      1034
DXVdsSTQphSYVmRchYKt      1016
Name: campaign, Length: 71, dtype: int64

In [111]:
device_df = pd.DataFrame()

col_list = ["os", "brand", "browser", "dsr", "country", "city"]

device_df[col_list] = total_df[col_list]
for item in col_list:
    item_df = pd.DataFrame()
    item_list = []

    item_df['name'] = device_df.groupby(by=[item], as_index=False)[item].max()
    item_df['count'] = device_df.groupby(by=[item], as_index=False)[item].count()
    item_list = item_df[item_df['count'] < 500].name.tolist()
    most_popular_item = device_df[item].mode().tolist()[0]

    for index_1 in item_list:
        item_index_list = []
        item_index_list = device_df[device_df[item] == index_1].index.tolist()
        device_df.loc[item_index_list, item] = most_popular_item

    total_df[item] = device_df[item].apply(lambda x: x)
    print(item)

os
brand
browser
dsr
country
city

In [113]:
total_df.to_csv('data/total_df_1.csv', index=False)